# Generated by Django 4.0.3 on 2023-10-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='designation',
            field=models.CharField(default='student', max_length=255),
        ),
    ]
